### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by pietgeursen** [p2panda/beep-beep-client#5]
Hey!
I must have missed this. Cool to see you're using bamboo-rs!

How are you licensing this work? Heads up,bamboo-rs is AGPL-3

**Comment by adzialocha** [comment]
Hi @pietgeursen, thanks for this fine library, we're planning on using it for the [p2panda protocol](github.com/p2panda/design-document) :panda_face: was pinging you a couple of times on ssb but maybe you've missed it!

And thanks for the reminder, just added the LICENSE (yes, also AGPL-3) for both the server and the client repository.
